version: '3'
include:
  - proxy.yaml
services:
  mysql:
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"

  test:
    image: nginx

  web:
    depends_on: ["mysql"]
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - web_data:/var/www/html
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
    ports:
      - 5000:5000
    environment:
      - DB_NAME=test
      - DB_USER=test
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=mysql 
volumes:
  db_data: {}
  web_data: {}
  

