# Используем базовый образ Python 3.9 slim
FROM python:3.9-slim

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем requirements.txt в контейнер
COPY requirements.txt /app

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы проекта в контейнер
COPY main.py .

# Указываем команду, которая будет выполняться при запуске контейнера
CMD ["python", "main.py"]